import type { EventItem } from "./EventSlideShow";

// Albums are ordered oldest to newest and correspond to entries on the
// Pack 365 Google Calendar. Photos live in /public/albums/<slug>/.
const eventList: EventItem[] = [
  {
    name: "Scouts Swimming & BBQ",
    description: "We had a wonderful time reconnecting with old friends and meeting new ones at the scouts swimming & BBQ event.",
    date: new Date(2025, 7, 19),
    photos: [
      { path: "/slideshow/IMG_0174.jpg", name: "Pool Area", description: "Kicking off the school year" },
      { path: "/slideshow/IMG_0176.jpg", name: "Enjoying Food and Friends", description: "Great turnout for the swimming event!" },
    ],
  },
  {
    name: "Onboarding @ Waters Edge",
    description: "Onboarding new scouts at Waters Edge Elementary",
    date: new Date(2025, 7, 21),
    photos: [
      { path: "/slideshow/IMG_0179.jpg", name: "Onboarding Photo 1", description: "Getting to know each other" },
      { path: "/slideshow/IMG_0181.jpg", name: "Onboarding Photo 2", description: "Team building activities" },
    ],
  },
  {
    name: "Onboarding @ Sandpiper Shores",
    description: "Onboarding new scouts at Sandpiper Shores Elementary",
    date: new Date(2025, 7, 28),
    photos: [
      { path: "/slideshow/IMG_0183.jpg", name: "Onboarding Photo 1", description: "Getting to know each other" },
      { path: "/slideshow/IMG_0186.jpg", name: "Onboarding Photo 2", description: "Team building activities" },
      { path: "/slideshow/IMG_0187.jpg", name: "Onboarding Photo 3", description: "Team building activities" },
      { path: "/slideshow/IMG_0184.jpg", name: "Onboarding Photo 4", description: "Team building activities" },
    ],
  },
  {
    name: "Popcorn Kickoff & Fundraiser",
    description: "The popcorn season, start to finish. After the kickoff the scouts took to the storefronts for the Trail's End sale — seventy percent of every sale stays local, funding a full year of camping, awards, and adventure.",
    date: new Date(2025, 7, 30),
    photos: [
      { path: "/slideshow/IMG_0190.jpg", name: "Popcorn Kickoff 1", description: "Excited scout ready to sell popcorn" },
      { path: "/slideshow/IMG_0192.jpg", name: "Popcorn Kickoff 2", description: "Gaining community support" },
      { path: "/albums/popcorn-fundraiser/popcorn-fundraiser-01.jpg", name: "Popcorn Kickoff & Fundraiser 1", description: "Show and sell outside the store" },
      { path: "/albums/popcorn-fundraiser/popcorn-fundraiser-02.jpg", name: "Popcorn Kickoff & Fundraiser 2", description: "Riding along on delivery day" },
      { path: "/albums/popcorn-fundraiser/popcorn-fundraiser-03.jpg", name: "Popcorn Kickoff & Fundraiser 3", description: "Wagon loaded for the neighborhood" },
      { path: "/albums/popcorn-fundraiser/popcorn-fundraiser-04.jpg", name: "Popcorn Kickoff & Fundraiser 4", description: "Working the table together" },
      { path: "/albums/popcorn-fundraiser/popcorn-fundraiser-05.jpg", name: "Popcorn Kickoff & Fundraiser 5", description: "The sales team on duty" },
      { path: "/albums/popcorn-fundraiser/popcorn-fundraiser-06.jpg", name: "Popcorn Kickoff & Fundraiser 6", description: "The full popcorn spread" },
      { path: "/albums/popcorn-fundraiser/popcorn-fundraiser-07.jpg", name: "Popcorn Kickoff & Fundraiser 7", description: "Inventory stacked to the ceiling" },
      { path: "/albums/popcorn-fundraiser/popcorn-fundraiser-08.jpg", name: "Popcorn Kickoff & Fundraiser 8", description: "Serenading the customers" },
    ],
  },
  {
    name: "Museum of Discovery Campout",
    description: "An overnight inside the Museum of Discovery and Science in Fort Lauderdale. Scouts built bridges, anchored the weather desk, explored the aquarium, and rolled out sleeping bags right under the exhibits.",
    date: new Date(2025, 8, 26),
    photos: [
      { path: "/albums/museum-of-discovery/museum-of-discovery-01.jpg", name: "Museum of Discovery Campout 1", description: "At the touch tank" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-02.jpg", name: "Museum of Discovery Campout 2", description: "Plasma: Ripping the Atom" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-03.jpg", name: "Museum of Discovery Campout 3", description: "Hands on the plasma dome" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-04.jpg", name: "Museum of Discovery Campout 4", description: "Inside the shark's jaws" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-05.jpg", name: "Museum of Discovery Campout 5", description: "Building at the engineering table" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-06.jpg", name: "Museum of Discovery Campout 6", description: "Comparing watershed models" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-07.jpg", name: "Museum of Discovery Campout 7", description: "Proud of her finished model" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-08.jpg", name: "Museum of Discovery Campout 8", description: "Testing reaction time" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-09.jpg", name: "Museum of Discovery Campout 9", description: "Leaders along for the overnight" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-10.jpg", name: "Museum of Discovery Campout 10", description: "Settling in for the show" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-11.jpg", name: "Museum of Discovery Campout 11", description: "Beds made up beside the habitat" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-12.jpg", name: "Museum of Discovery Campout 12", description: "Riding the dinosaur" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-13.jpg", name: "Museum of Discovery Campout 13", description: "Swallowed by the exhibit" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-14.jpg", name: "Museum of Discovery Campout 14", description: "Anchoring the weather desk" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-15.jpg", name: "Museum of Discovery Campout 15", description: "Digging in the fossil pit" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-16.jpg", name: "Museum of Discovery Campout 16", description: "Exploring the flight gallery" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-17.jpg", name: "Museum of Discovery Campout 17", description: "Coaching the build" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-18.jpg", name: "Museum of Discovery Campout 18", description: "Leaders on the overnight" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-19.jpg", name: "Museum of Discovery Campout 19", description: "Reaction time, zeroed out" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-20.jpg", name: "Museum of Discovery Campout 20", description: "Under the mammoth" },
      { path: "/albums/museum-of-discovery/museum-of-discovery-21.jpg", name: "Museum of Discovery Campout 21", description: "Paper airplanes and paint" },
    ],
  },
  {
    name: "Cub Halloween Camp Out",
    description: "The all-ages Halloween campout at Camp La-No-Che. Costumes, a haunted trail, campfire shows, BB range time, and a weekend of cool-weather camping in the pines.",
    date: new Date(2025, 9, 17),
    photos: [
      { path: "/albums/cub-halloween/cub-halloween-01.jpg", name: "Cub Halloween Camp Out 1", description: "Night hike back to camp" },
      { path: "/albums/cub-halloween/cub-halloween-02.jpg", name: "Cub Halloween Camp Out 2", description: "Dining hall dinner" },
      { path: "/albums/cub-halloween/cub-halloween-03.jpg", name: "Cub Halloween Camp Out 3", description: "Gathering on the parade ground" },
      { path: "/albums/cub-halloween/cub-halloween-04.jpg", name: "Cub Halloween Camp Out 4", description: "Lunch under the pavilion" },
      { path: "/albums/cub-halloween/cub-halloween-05.jpg", name: "Cub Halloween Camp Out 5", description: "Digging in the sand" },
      { path: "/albums/cub-halloween/cub-halloween-06.jpg", name: "Cub Halloween Camp Out 6", description: "On the archery line" },
      { path: "/albums/cub-halloween/cub-halloween-07.jpg", name: "Cub Halloween Camp Out 7", description: "Taking aim" },
      { path: "/albums/cub-halloween/cub-halloween-08.jpg", name: "Cub Halloween Camp Out 8", description: "Family at the range" },
      { path: "/albums/cub-halloween/cub-halloween-09.jpg", name: "Cub Halloween Camp Out 9", description: "Nocking an arrow" },
      { path: "/albums/cub-halloween/cub-halloween-10.jpg", name: "Cub Halloween Camp Out 10", description: "Waiting for the next round" },
      { path: "/albums/cub-halloween/cub-halloween-11.jpg", name: "Cub Halloween Camp Out 11", description: "BB range, lane 13" },
      { path: "/albums/cub-halloween/cub-halloween-12.jpg", name: "Cub Halloween Camp Out 12", description: "Lining up at the targets" },
      { path: "/albums/cub-halloween/cub-halloween-13.jpg", name: "Cub Halloween Camp Out 13", description: "Camp in the pines" },
      { path: "/albums/cub-halloween/cub-halloween-14.jpg", name: "Cub Halloween Camp Out 14", description: "Riding out to the next station" },
      { path: "/albums/cub-halloween/cub-halloween-15.jpg", name: "Cub Halloween Camp Out 15", description: "A visitor on the trail" },
      { path: "/albums/cub-halloween/cub-halloween-16.jpg", name: "Cub Halloween Camp Out 16", description: "Thumbs up in the pool" },
      { path: "/albums/cub-halloween/cub-halloween-17.jpg", name: "Cub Halloween Camp Out 17", description: "Poolside on a warm afternoon" },
      { path: "/albums/cub-halloween/cub-halloween-18.jpg", name: "Cub Halloween Camp Out 18", description: "Pool games" },
      { path: "/albums/cub-halloween/cub-halloween-19.jpg", name: "Cub Halloween Camp Out 19", description: "Swimming laps" },
      { path: "/albums/cub-halloween/cub-halloween-20.jpg", name: "Cub Halloween Camp Out 20", description: "Wrapped up after the swim" },
      { path: "/albums/cub-halloween/cub-halloween-21.jpg", name: "Cub Halloween Camp Out 21", description: "Fishing the lake shore" },
      { path: "/albums/cub-halloween/cub-halloween-22.jpg", name: "Cub Halloween Camp Out 22", description: "Casting from the bank" },
      { path: "/albums/cub-halloween/cub-halloween-23.jpg", name: "Cub Halloween Camp Out 23", description: "Skeleton scouts on duty" },
      { path: "/albums/cub-halloween/cub-halloween-24.jpg", name: "Cub Halloween Camp Out 24", description: "The Slaughterhouse trail" },
      { path: "/albums/cub-halloween/cub-halloween-25.jpg", name: "Cub Halloween Camp Out 25", description: "Campfire show" },
      { path: "/albums/cub-halloween/cub-halloween-26.jpg", name: "Cub Halloween Camp Out 26", description: "The haunted barn" },
      { path: "/albums/cub-halloween/cub-halloween-27.jpg", name: "Cub Halloween Camp Out 27", description: "Masks in the dark" },
      { path: "/albums/cub-halloween/cub-halloween-28.jpg", name: "Cub Halloween Camp Out 28", description: "Skeletons in uniform" },
      { path: "/albums/cub-halloween/cub-halloween-29.jpg", name: "Cub Halloween Camp Out 29", description: "Butterfly wings" },
      { path: "/albums/cub-halloween/cub-halloween-30.jpg", name: "Cub Halloween Camp Out 30", description: "Pumpkin carving" },
      { path: "/albums/cub-halloween/cub-halloween-31.jpg", name: "Cub Halloween Camp Out 31", description: "Afternoon at the pool" },
      { path: "/albums/cub-halloween/cub-halloween-32.jpg", name: "Cub Halloween Camp Out 32", description: "Snack break at the picnic table" },
    ],
  },
  {
    name: "Scouts Trunk or Treat",
    description: "Families decked out their trunks and the parking lot at Waters Edge Elementary turned into a Halloween midway. Costumes, candy, and some seriously committed decorating.",
    date: new Date(2025, 9, 30),
    photos: [
      { path: "/albums/trunk-or-treat/trunk-or-treat-01.jpg", name: "Scouts Trunk or Treat 1", description: "Buckets ready" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-02.jpg", name: "Scouts Trunk or Treat 2", description: "Clown car selfie" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-03.jpg", name: "Scouts Trunk or Treat 3", description: "Costumes and candy bags" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-04.jpg", name: "Scouts Trunk or Treat 4", description: "Penguin on the loose" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-05.jpg", name: "Scouts Trunk or Treat 5", description: "The whole crowd at sunset" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-06.jpg", name: "Scouts Trunk or Treat 6", description: "Motorcycle ghost rider" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-07.jpg", name: "Scouts Trunk or Treat 7", description: "Skeleton pickup truck" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-08.jpg", name: "Scouts Trunk or Treat 8", description: "Making the rounds" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-09.jpg", name: "Scouts Trunk or Treat 9", description: "Witch hats and flames" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-10.jpg", name: "Scouts Trunk or Treat 10", description: "Ghosts at the tailgate" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-11.jpg", name: "Scouts Trunk or Treat 11", description: "Skeletons and spider webs" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-12.jpg", name: "Scouts Trunk or Treat 12", description: "Aliens landed in the lot" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-13.jpg", name: "Scouts Trunk or Treat 13", description: "Marshmello and friends" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-14.jpg", name: "Scouts Trunk or Treat 14", description: "Family in costume" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-15.jpg", name: "Scouts Trunk or Treat 15", description: "Trunks lit up at dusk" },
      { path: "/albums/trunk-or-treat/trunk-or-treat-16.jpg", name: "Scouts Trunk or Treat 16", description: "Happy Halloween banner" },
    ],
  },
  {
    name: "All Ages Camping — Tanah Keeta",
    description: "A full weekend at Tanah Keeta Scout Reservation. Canoeing on the water, hiking the trails, cooking out, and a campfire that brought the whole pack together.",
    date: new Date(2025, 10, 7),
    photos: [
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-01.jpg", name: "All Ages Camping — Tanah Keeta 1", description: "Gaga ball after dark" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-02.jpg", name: "All Ages Camping — Tanah Keeta 2", description: "Campfire roaring" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-03.jpg", name: "All Ages Camping — Tanah Keeta 3", description: "Circled up around the fire" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-04.jpg", name: "All Ages Camping — Tanah Keeta 4", description: "Sparks and stories" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-05.jpg", name: "All Ages Camping — Tanah Keeta 5", description: "Camp kitchen crew" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-06.jpg", name: "All Ages Camping — Tanah Keeta 6", description: "Arms wide at the waterfront" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-07.jpg", name: "All Ages Camping — Tanah Keeta 7", description: "Canoe selfie" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-08.jpg", name: "All Ages Camping — Tanah Keeta 8", description: "Out on the water" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-09.jpg", name: "All Ages Camping — Tanah Keeta 9", description: "The lake in the pines" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-10.jpg", name: "All Ages Camping — Tanah Keeta 10", description: "Paddles up" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-11.jpg", name: "All Ages Camping — Tanah Keeta 11", description: "Cruising the far bank" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-12.jpg", name: "All Ages Camping — Tanah Keeta 12", description: "Family canoe" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-13.jpg", name: "All Ages Camping — Tanah Keeta 13", description: "Working the paddle" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-14.jpg", name: "All Ages Camping — Tanah Keeta 14", description: "Two boats out" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-15.jpg", name: "All Ages Camping — Tanah Keeta 15", description: "Steady in the canoe" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-16.jpg", name: "All Ages Camping — Tanah Keeta 16", description: "Waving from the water" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-17.jpg", name: "All Ages Camping — Tanah Keeta 17", description: "Full canoe on the lake" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-18.jpg", name: "All Ages Camping — Tanah Keeta 18", description: "Gliding past the pines" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-19.jpg", name: "All Ages Camping — Tanah Keeta 19", description: "Waiting on the launch" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-20.jpg", name: "All Ages Camping — Tanah Keeta 20", description: "Life jackets on" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-21.jpg", name: "All Ages Camping — Tanah Keeta 21", description: "Crew of four" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-22.jpg", name: "All Ages Camping — Tanah Keeta 22", description: "Break on the bench" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-23.jpg", name: "All Ages Camping — Tanah Keeta 23", description: "Folding the flag" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-24.jpg", name: "All Ages Camping — Tanah Keeta 24", description: "Under the pavilion" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-25.jpg", name: "All Ages Camping — Tanah Keeta 25", description: "Den on the shoreline" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-26.jpg", name: "All Ages Camping — Tanah Keeta 26", description: "The whole pack, hands up" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-27.jpg", name: "All Ages Camping — Tanah Keeta 27", description: "Everybody in the picture" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-28.jpg", name: "All Ages Camping — Tanah Keeta 28", description: "Refilling the water jugs" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-29.jpg", name: "All Ages Camping — Tanah Keeta 29", description: "Buddies at lunch" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-30.jpg", name: "All Ages Camping — Tanah Keeta 30", description: "Ready for the flag ceremony" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-31.jpg", name: "All Ages Camping — Tanah Keeta 31", description: "Around the fire at night" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-32.jpg", name: "All Ages Camping — Tanah Keeta 32", description: "Late night in the pavilion" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-33.jpg", name: "All Ages Camping — Tanah Keeta 33", description: "Air hockey under the roof" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-34.jpg", name: "All Ages Camping — Tanah Keeta 34", description: "Over the climbing wall" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-35.jpg", name: "All Ages Camping — Tanah Keeta 35", description: "Tents pitched and ready" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-36.jpg", name: "All Ages Camping — Tanah Keeta 36", description: "Marshmallows over the coals" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-37.jpg", name: "All Ages Camping — Tanah Keeta 37", description: "Big fire, bigger crowd" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-38.jpg", name: "All Ages Camping — Tanah Keeta 38", description: "Boarding the canoe" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-39.jpg", name: "All Ages Camping — Tanah Keeta 39", description: "Paddling out together" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-40.jpg", name: "All Ages Camping — Tanah Keeta 40", description: "Three in a canoe" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-41.jpg", name: "All Ages Camping — Tanah Keeta 41", description: "Rain gutter regatta" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-42.jpg", name: "All Ages Camping — Tanah Keeta 42", description: "Up and over the wall" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-43.jpg", name: "All Ages Camping — Tanah Keeta 43", description: "The obstacle ramp" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-44.jpg", name: "All Ages Camping — Tanah Keeta 44", description: "Pancakes on the griddle" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-45.jpg", name: "All Ages Camping — Tanah Keeta 45", description: "Around the fire ring" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-46.jpg", name: "All Ages Camping — Tanah Keeta 46", description: "Toasted just right" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-47.jpg", name: "All Ages Camping — Tanah Keeta 47", description: "Marshmallow on a stick" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-48.jpg", name: "All Ages Camping — Tanah Keeta 48", description: "Setting up camp together" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-49.jpg", name: "All Ages Camping — Tanah Keeta 49", description: "Walking to the next station" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-50.jpg", name: "All Ages Camping — Tanah Keeta 50", description: "Rain gutter regatta setup" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-51.jpg", name: "All Ages Camping — Tanah Keeta 51", description: "Camp kitchen at work" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-52.jpg", name: "All Ages Camping — Tanah Keeta 52", description: "Craft table under the pavilion" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-53.jpg", name: "All Ages Camping — Tanah Keeta 53", description: "Bonfire night" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-54.jpg", name: "All Ages Camping — Tanah Keeta 54", description: "Scaling the A-frame" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-55.jpg", name: "All Ages Camping — Tanah Keeta 55", description: "Camp headquarters" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-56.jpg", name: "All Ages Camping — Tanah Keeta 56", description: "Hanging out at the picnic tables" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-57.jpg", name: "All Ages Camping — Tanah Keeta 57", description: "Down the other side" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-58.jpg", name: "All Ages Camping — Tanah Keeta 58", description: "Trail break" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-59.jpg", name: "All Ages Camping — Tanah Keeta 59", description: "Pogo stick champion" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-60.jpg", name: "All Ages Camping — Tanah Keeta 60", description: "On the archery line" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-61.jpg", name: "All Ages Camping — Tanah Keeta 61", description: "Football in the field" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-62.jpg", name: "All Ages Camping — Tanah Keeta 62", description: "Waiting by the trailer" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-63.jpg", name: "All Ages Camping — Tanah Keeta 63", description: "Prepping foil dinners" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-64.jpg", name: "All Ages Camping — Tanah Keeta 64", description: "Foil dinner, ready to cook" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-65.jpg", name: "All Ages Camping — Tanah Keeta 65", description: "Gaga ball under the lights" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-66.jpg", name: "All Ages Camping — Tanah Keeta 66", description: "Dish duty" },
      { path: "/albums/tanah-keeta-november/tanah-keeta-november-67.jpg", name: "All Ages Camping — Tanah Keeta 67", description: "Manning the griddle" },
    ],
  },
  {
    name: "Veterans Day Ceremony",
    description: "Pack 365 presented colors and lined the route for the Veterans Day ceremony, flags in hand, honoring those who served.",
    date: new Date(2025, 10, 11),
    photos: [
      { path: "/albums/veterans-day/veterans-day-01.jpg", name: "Veterans Day Ceremony 1", description: "Flags against the ladder truck" },
      { path: "/albums/veterans-day/veterans-day-02.jpg", name: "Veterans Day Ceremony 2", description: "With Palm Beach County Fire Rescue" },
      { path: "/albums/veterans-day/veterans-day-03.jpg", name: "Veterans Day Ceremony 3", description: "Standing at attention" },
      { path: "/albums/veterans-day/veterans-day-04.jpg", name: "Veterans Day Ceremony 4", description: "Lining the route" },
      { path: "/albums/veterans-day/veterans-day-05.jpg", name: "Veterans Day Ceremony 5", description: "Flags in hand" },
      { path: "/albums/veterans-day/veterans-day-06.jpg", name: "Veterans Day Ceremony 6", description: "Long shadows on the road" },
      { path: "/albums/veterans-day/veterans-day-07.jpg", name: "Veterans Day Ceremony 7", description: "Scouts and leaders in formation" },
      { path: "/albums/veterans-day/veterans-day-08.jpg", name: "Veterans Day Ceremony 8", description: "Waiting for the procession" },
      { path: "/albums/veterans-day/veterans-day-09.jpg", name: "Veterans Day Ceremony 9", description: "Color guard assembled" },
      { path: "/albums/veterans-day/veterans-day-10.jpg", name: "Veterans Day Ceremony 10", description: "The colors pass by" },
      { path: "/albums/veterans-day/veterans-day-11.jpg", name: "Veterans Day Ceremony 11", description: "Marching in" },
      { path: "/albums/veterans-day/veterans-day-12.jpg", name: "Veterans Day Ceremony 12", description: "Flags at the memorial" },
      { path: "/albums/veterans-day/veterans-day-13.jpg", name: "Veterans Day Ceremony 13", description: "Pack 365 color guard" },
    ],
  },
  {
    name: "All Ages Camping — Camp Elmore",
    description: "A weekend at Camp Elmore built around the range: archery, BB guns, and target sports, with lakeside walks and camp cooking in between.",
    date: new Date(2025, 11, 5),
    photos: [
      { path: "/albums/camp-elmore/camp-elmore-01.jpg", name: "All Ages Camping — Camp Elmore 1", description: "Coaching the first shot" },
      { path: "/albums/camp-elmore/camp-elmore-02.jpg", name: "All Ages Camping — Camp Elmore 2", description: "Learning the draw" },
      { path: "/albums/camp-elmore/camp-elmore-03.jpg", name: "All Ages Camping — Camp Elmore 3", description: "Buddies at the archery range" },
      { path: "/albums/camp-elmore/camp-elmore-04.jpg", name: "All Ages Camping — Camp Elmore 4", description: "Steadying the bow" },
      { path: "/albums/camp-elmore/camp-elmore-05.jpg", name: "All Ages Camping — Camp Elmore 5", description: "BB range under the pavilion" },
      { path: "/albums/camp-elmore/camp-elmore-06.jpg", name: "All Ages Camping — Camp Elmore 6", description: "Down the firing line" },
      { path: "/albums/camp-elmore/camp-elmore-07.jpg", name: "All Ages Camping — Camp Elmore 7", description: "Gaga ball pit" },
      { path: "/albums/camp-elmore/camp-elmore-08.jpg", name: "All Ages Camping — Camp Elmore 8", description: "Camp cooking" },
      { path: "/albums/camp-elmore/camp-elmore-09.jpg", name: "All Ages Camping — Camp Elmore 9", description: "Dinner under the tent" },
      { path: "/albums/camp-elmore/camp-elmore-10.jpg", name: "All Ages Camping — Camp Elmore 10", description: "Lunch break" },
      { path: "/albums/camp-elmore/camp-elmore-11.jpg", name: "All Ages Camping — Camp Elmore 11", description: "The whole camp at the table" },
      { path: "/albums/camp-elmore/camp-elmore-12.jpg", name: "All Ages Camping — Camp Elmore 12", description: "Breakfast together" },
      { path: "/albums/camp-elmore/camp-elmore-13.jpg", name: "All Ages Camping — Camp Elmore 13", description: "Serving line" },
      { path: "/albums/camp-elmore/camp-elmore-14.jpg", name: "All Ages Camping — Camp Elmore 14", description: "Full draw" },
      { path: "/albums/camp-elmore/camp-elmore-15.jpg", name: "All Ages Camping — Camp Elmore 15", description: "Ready to release" },
      { path: "/albums/camp-elmore/camp-elmore-16.jpg", name: "All Ages Camping — Camp Elmore 16", description: "Eyes on the target" },
      { path: "/albums/camp-elmore/camp-elmore-17.jpg", name: "All Ages Camping — Camp Elmore 17", description: "Hanging around the range" },
      { path: "/albums/camp-elmore/camp-elmore-18.jpg", name: "All Ages Camping — Camp Elmore 18", description: "Taking aim" },
      { path: "/albums/camp-elmore/camp-elmore-19.jpg", name: "All Ages Camping — Camp Elmore 19", description: "Arrows on target" },
      { path: "/albums/camp-elmore/camp-elmore-20.jpg", name: "All Ages Camping — Camp Elmore 20", description: "Coaching the release" },
      { path: "/albums/camp-elmore/camp-elmore-21.jpg", name: "All Ages Camping — Camp Elmore 21", description: "Side by side on the line" },
      { path: "/albums/camp-elmore/camp-elmore-22.jpg", name: "All Ages Camping — Camp Elmore 22", description: "Focused on the shot" },
      { path: "/albums/camp-elmore/camp-elmore-23.jpg", name: "All Ages Camping — Camp Elmore 23", description: "A Pack 365 leader on the line" },
      { path: "/albums/camp-elmore/camp-elmore-24.jpg", name: "All Ages Camping — Camp Elmore 24", description: "Steady aim" },
      { path: "/albums/camp-elmore/camp-elmore-25.jpg", name: "All Ages Camping — Camp Elmore 25", description: "Adult archery round" },
      { path: "/albums/camp-elmore/camp-elmore-26.jpg", name: "All Ages Camping — Camp Elmore 26", description: "Standing shot" },
      { path: "/albums/camp-elmore/camp-elmore-27.jpg", name: "All Ages Camping — Camp Elmore 27", description: "Family at the BB range" },
      { path: "/albums/camp-elmore/camp-elmore-28.jpg", name: "All Ages Camping — Camp Elmore 28", description: "Safety glasses on" },
      { path: "/albums/camp-elmore/camp-elmore-29.jpg", name: "All Ages Camping — Camp Elmore 29", description: "Sighting down the barrel" },
      { path: "/albums/camp-elmore/camp-elmore-30.jpg", name: "All Ages Camping — Camp Elmore 30", description: "Lining up the shot" },
      { path: "/albums/camp-elmore/camp-elmore-31.jpg", name: "All Ages Camping — Camp Elmore 31", description: "Steady on the rest" },
      { path: "/albums/camp-elmore/camp-elmore-32.jpg", name: "All Ages Camping — Camp Elmore 32", description: "Concentrating on the target" },
      { path: "/albums/camp-elmore/camp-elmore-33.jpg", name: "All Ages Camping — Camp Elmore 33", description: "Getting a hand with the aim" },
      { path: "/albums/camp-elmore/camp-elmore-34.jpg", name: "All Ages Camping — Camp Elmore 34", description: "On the bench rest" },
      { path: "/albums/camp-elmore/camp-elmore-35.jpg", name: "All Ages Camping — Camp Elmore 35", description: "Coaching from behind" },
      { path: "/albums/camp-elmore/camp-elmore-36.jpg", name: "All Ages Camping — Camp Elmore 36", description: "Standing at the rail" },
      { path: "/albums/camp-elmore/camp-elmore-37.jpg", name: "All Ages Camping — Camp Elmore 37", description: "A leader takes a turn" },
      { path: "/albums/camp-elmore/camp-elmore-38.jpg", name: "All Ages Camping — Camp Elmore 38", description: "Fishing the canal" },
      { path: "/albums/camp-elmore/camp-elmore-39.jpg", name: "All Ages Camping — Camp Elmore 39", description: "Rigging up the rods" },
      { path: "/albums/camp-elmore/camp-elmore-40.jpg", name: "All Ages Camping — Camp Elmore 40", description: "Face paint and fishing poles" },
      { path: "/albums/camp-elmore/camp-elmore-41.jpg", name: "All Ages Camping — Camp Elmore 41", description: "Hauling the gear wagon" },
      { path: "/albums/camp-elmore/camp-elmore-42.jpg", name: "All Ages Camping — Camp Elmore 42", description: "Trying the BB range" },
      { path: "/albums/camp-elmore/camp-elmore-43.jpg", name: "All Ages Camping — Camp Elmore 43", description: "Shouldering the rifle" },
      { path: "/albums/camp-elmore/camp-elmore-44.jpg", name: "All Ages Camping — Camp Elmore 44", description: "Lining up carefully" },
      { path: "/albums/camp-elmore/camp-elmore-45.jpg", name: "All Ages Camping — Camp Elmore 45", description: "Two generations on the line" },
      { path: "/albums/camp-elmore/camp-elmore-46.jpg", name: "All Ages Camping — Camp Elmore 46", description: "Sunset catch" },
      { path: "/albums/camp-elmore/camp-elmore-47.jpg", name: "All Ages Camping — Camp Elmore 47", description: "Down by the lake" },
      { path: "/albums/camp-elmore/camp-elmore-48.jpg", name: "All Ages Camping — Camp Elmore 48", description: "Casting from the bank" },
      { path: "/albums/camp-elmore/camp-elmore-49.jpg", name: "All Ages Camping — Camp Elmore 49", description: "Snack break on the bench" },
      { path: "/albums/camp-elmore/camp-elmore-50.jpg", name: "All Ages Camping — Camp Elmore 50", description: "First catch of the day" },
      { path: "/albums/camp-elmore/camp-elmore-51.jpg", name: "All Ages Camping — Camp Elmore 51", description: "Two anglers, one fish" },
      { path: "/albums/camp-elmore/camp-elmore-52.jpg", name: "All Ages Camping — Camp Elmore 52", description: "Comparing catches at dusk" },
      { path: "/albums/camp-elmore/camp-elmore-53.jpg", name: "All Ages Camping — Camp Elmore 53", description: "Proud of the catch" },
      { path: "/albums/camp-elmore/camp-elmore-54.jpg", name: "All Ages Camping — Camp Elmore 54", description: "Bonfire at dusk" },
      { path: "/albums/camp-elmore/camp-elmore-55.jpg", name: "All Ages Camping — Camp Elmore 55", description: "Group hug" },
      { path: "/albums/camp-elmore/camp-elmore-56.jpg", name: "All Ages Camping — Camp Elmore 56", description: "Piggyback races" },
      { path: "/albums/camp-elmore/camp-elmore-57.jpg", name: "All Ages Camping — Camp Elmore 57", description: "Games on the patio" },
      { path: "/albums/camp-elmore/camp-elmore-58.jpg", name: "All Ages Camping — Camp Elmore 58", description: "Learning to shoot together" },
      { path: "/albums/camp-elmore/camp-elmore-59.jpg", name: "All Ages Camping — Camp Elmore 59", description: "Getting set on the line" },
      { path: "/albums/camp-elmore/camp-elmore-60.jpg", name: "All Ages Camping — Camp Elmore 60", description: "Building at the picnic table" },
      { path: "/albums/camp-elmore/camp-elmore-61.jpg", name: "All Ages Camping — Camp Elmore 61", description: "The whole line at the range" },
      { path: "/albums/camp-elmore/camp-elmore-62.jpg", name: "All Ages Camping — Camp Elmore 62", description: "Alone at the targets" },
      { path: "/albums/camp-elmore/camp-elmore-63.jpg", name: "All Ages Camping — Camp Elmore 63", description: "Iguana in the tree" },
      { path: "/albums/camp-elmore/camp-elmore-64.jpg", name: "All Ages Camping — Camp Elmore 64", description: "Spider web at night" },
      { path: "/albums/camp-elmore/camp-elmore-65.jpg", name: "All Ages Camping — Camp Elmore 65", description: "Campfire on the field" },
      { path: "/albums/camp-elmore/camp-elmore-66.jpg", name: "All Ages Camping — Camp Elmore 66", description: "Night crafts" },
      { path: "/albums/camp-elmore/camp-elmore-67.jpg", name: "All Ages Camping — Camp Elmore 67", description: "Shouldering up together" },
      { path: "/albums/camp-elmore/camp-elmore-68.jpg", name: "All Ages Camping — Camp Elmore 68", description: "Gaga pit in the daylight" },
    ],
  },
  {
    name: "Pack 365 Community Service Project",
    description: "The pack showed up at Sandpiper Shores Elementary to rebuild the school garden — hauling mulch, clearing beds, planting, and watering. A good, muddy morning of giving back.",
    date: new Date(2026, 0, 11),
    photos: [
      { path: "/albums/service-project/service-project-01.jpg", name: "Pack 365 Community Service Project 1", description: "Breaking ground on the garden" },
      { path: "/albums/service-project/service-project-02.jpg", name: "Pack 365 Community Service Project 2", description: "Raking out the beds" },
      { path: "/albums/service-project/service-project-03.jpg", name: "Pack 365 Community Service Project 3", description: "Sweeping the walkway" },
      { path: "/albums/service-project/service-project-04.jpg", name: "Pack 365 Community Service Project 4", description: "Digging in" },
      { path: "/albums/service-project/service-project-05.jpg", name: "Pack 365 Community Service Project 5", description: "Hauling the planter barrel" },
      { path: "/albums/service-project/service-project-06.jpg", name: "Pack 365 Community Service Project 6", description: "Tools and volunteers" },
      { path: "/albums/service-project/service-project-07.jpg", name: "Pack 365 Community Service Project 7", description: "Painting garden signs" },
      { path: "/albums/service-project/service-project-08.jpg", name: "Pack 365 Community Service Project 8", description: "The whole crew at the garden" },
      { path: "/albums/service-project/service-project-09.jpg", name: "Pack 365 Community Service Project 9", description: "Wagon brigade" },
      { path: "/albums/service-project/service-project-10.jpg", name: "Pack 365 Community Service Project 10", description: "Filling the raised beds" },
      { path: "/albums/service-project/service-project-11.jpg", name: "Pack 365 Community Service Project 11", description: "Spreading soil" },
      { path: "/albums/service-project/service-project-12.jpg", name: "Pack 365 Community Service Project 12", description: "Clearing the overgrowth" },
      { path: "/albums/service-project/service-project-13.jpg", name: "Pack 365 Community Service Project 13", description: "Watering cans ready" },
      { path: "/albums/service-project/service-project-14.jpg", name: "Pack 365 Community Service Project 14", description: "Fetching more water" },
      { path: "/albums/service-project/service-project-15.jpg", name: "Pack 365 Community Service Project 15", description: "Planting the seedlings" },
      { path: "/albums/service-project/service-project-16.jpg", name: "Pack 365 Community Service Project 16", description: "Beds filled and planted" },
      { path: "/albums/service-project/service-project-17.jpg", name: "Pack 365 Community Service Project 17", description: "Working the soil" },
      { path: "/albums/service-project/service-project-18.jpg", name: "Pack 365 Community Service Project 18", description: "Shoveling into the frame" },
      { path: "/albums/service-project/service-project-19.jpg", name: "Pack 365 Community Service Project 19", description: "Turning the beds over" },
      { path: "/albums/service-project/service-project-20.jpg", name: "Pack 365 Community Service Project 20", description: "Planting as a team" },
      { path: "/albums/service-project/service-project-21.jpg", name: "Pack 365 Community Service Project 21", description: "Digging out the old bed" },
      { path: "/albums/service-project/service-project-22.jpg", name: "Pack 365 Community Service Project 22", description: "The whole pack with the finished beds" },
      { path: "/albums/service-project/service-project-23.jpg", name: "Pack 365 Community Service Project 23", description: "Ready with the tools" },
      { path: "/albums/service-project/service-project-24.jpg", name: "Pack 365 Community Service Project 24", description: "Watering the new plants" },
      { path: "/albums/service-project/service-project-25.jpg", name: "Pack 365 Community Service Project 25", description: "Giving the seedlings a drink" },
      { path: "/albums/service-project/service-project-26.jpg", name: "Pack 365 Community Service Project 26", description: "Setting the plants in" },
      { path: "/albums/service-project/service-project-27.jpg", name: "Pack 365 Community Service Project 27", description: "A good soak" },
      { path: "/albums/service-project/service-project-28.jpg", name: "Pack 365 Community Service Project 28", description: "Everyone pitching in" },
      { path: "/albums/service-project/service-project-29.jpg", name: "Pack 365 Community Service Project 29", description: "The finished garden" },
      { path: "/albums/service-project/service-project-30.jpg", name: "Pack 365 Community Service Project 30", description: "Planting the last row" },
      { path: "/albums/service-project/service-project-31.jpg", name: "Pack 365 Community Service Project 31", description: "Lining up at the Sandpiper Cafe" },
    ],
  },
  {
    name: "All Ages Camping — WDW Fort Wilderness",
    description: "Three nights at Disney's Fort Wilderness over a cold snap. Horseback riding, canoes, tie-dye, the Hoop-Dee-Doo Revue, campfire singalongs, and deer wandering through camp.",
    date: new Date(2026, 0, 16),
    photos: [
      { path: "/albums/ft-wilderness/ft-wilderness-01.jpg", name: "All Ages Camping — WDW Fort Wilderness 1", description: "Deer beside the road" },
      { path: "/albums/ft-wilderness/ft-wilderness-02.jpg", name: "All Ages Camping — WDW Fort Wilderness 2", description: "Warming up by the fire" },
      { path: "/albums/ft-wilderness/ft-wilderness-03.jpg", name: "All Ages Camping — WDW Fort Wilderness 3", description: "On the tram" },
      { path: "/albums/ft-wilderness/ft-wilderness-04.jpg", name: "All Ages Camping — WDW Fort Wilderness 4", description: "Golf cart all lit up" },
      { path: "/albums/ft-wilderness/ft-wilderness-05.jpg", name: "All Ages Camping — WDW Fort Wilderness 5", description: "Lunch by the water" },
      { path: "/albums/ft-wilderness/ft-wilderness-06.jpg", name: "All Ages Camping — WDW Fort Wilderness 6", description: "Exploring the grounds" },
      { path: "/albums/ft-wilderness/ft-wilderness-07.jpg", name: "All Ages Camping — WDW Fort Wilderness 7", description: "Family photo at the resort" },
      { path: "/albums/ft-wilderness/ft-wilderness-08.jpg", name: "All Ages Camping — WDW Fort Wilderness 8", description: "At the coaster" },
      { path: "/albums/ft-wilderness/ft-wilderness-09.jpg", name: "All Ages Camping — WDW Fort Wilderness 9", description: "Golf cart selfie" },
      { path: "/albums/ft-wilderness/ft-wilderness-10.jpg", name: "All Ages Camping — WDW Fort Wilderness 10", description: "Hoop-Dee-Doo Revue" },
      { path: "/albums/ft-wilderness/ft-wilderness-11.jpg", name: "All Ages Camping — WDW Fort Wilderness 11", description: "Dinner and a show" },
      { path: "/albums/ft-wilderness/ft-wilderness-12.jpg", name: "All Ages Camping — WDW Fort Wilderness 12", description: "The whole group at Pioneer Hall" },
      { path: "/albums/ft-wilderness/ft-wilderness-13.jpg", name: "All Ages Camping — WDW Fort Wilderness 13", description: "Volleyball in the sand" },
      { path: "/albums/ft-wilderness/ft-wilderness-14.jpg", name: "All Ages Camping — WDW Fort Wilderness 14", description: "S'mores at the fire pit" },
      { path: "/albums/ft-wilderness/ft-wilderness-15.jpg", name: "All Ages Camping — WDW Fort Wilderness 15", description: "Campfire singalong" },
      { path: "/albums/ft-wilderness/ft-wilderness-16.jpg", name: "All Ages Camping — WDW Fort Wilderness 16", description: "Warming up after dark" },
      { path: "/albums/ft-wilderness/ft-wilderness-17.jpg", name: "All Ages Camping — WDW Fort Wilderness 17", description: "Cocoa break in the pines" },
      { path: "/albums/ft-wilderness/ft-wilderness-18.jpg", name: "All Ages Camping — WDW Fort Wilderness 18", description: "Piled into the golf cart" },
      { path: "/albums/ft-wilderness/ft-wilderness-19.jpg", name: "All Ages Camping — WDW Fort Wilderness 19", description: "Pool table tournament" },
      { path: "/albums/ft-wilderness/ft-wilderness-20.jpg", name: "All Ages Camping — WDW Fort Wilderness 20", description: "Ping pong under the pavilion" },
      { path: "/albums/ft-wilderness/ft-wilderness-21.jpg", name: "All Ages Camping — WDW Fort Wilderness 21", description: "Racking up another game" },
      { path: "/albums/ft-wilderness/ft-wilderness-22.jpg", name: "All Ages Camping — WDW Fort Wilderness 22", description: "Hand warmers all around" },
      { path: "/albums/ft-wilderness/ft-wilderness-23.jpg", name: "All Ages Camping — WDW Fort Wilderness 23", description: "Family at Pioneer Hall" },
      { path: "/albums/ft-wilderness/ft-wilderness-24.jpg", name: "All Ages Camping — WDW Fort Wilderness 24", description: "Late game of pool" },
      { path: "/albums/ft-wilderness/ft-wilderness-25.jpg", name: "All Ages Camping — WDW Fort Wilderness 25", description: "Tie-dye station" },
      { path: "/albums/ft-wilderness/ft-wilderness-26.jpg", name: "All Ages Camping — WDW Fort Wilderness 26", description: "Canoes at the waterfront" },
      { path: "/albums/ft-wilderness/ft-wilderness-27.jpg", name: "All Ages Camping — WDW Fort Wilderness 27", description: "Kayaking the canal" },
      { path: "/albums/ft-wilderness/ft-wilderness-28.jpg", name: "All Ages Camping — WDW Fort Wilderness 28", description: "Paddling under the bridge" },
      { path: "/albums/ft-wilderness/ft-wilderness-29.jpg", name: "All Ages Camping — WDW Fort Wilderness 29", description: "Panning for gemstones" },
      { path: "/albums/ft-wilderness/ft-wilderness-30.jpg", name: "All Ages Camping — WDW Fort Wilderness 30", description: "Craft table by the water" },
      { path: "/albums/ft-wilderness/ft-wilderness-31.jpg", name: "All Ages Camping — WDW Fort Wilderness 31", description: "Faces in the totem" },
      { path: "/albums/ft-wilderness/ft-wilderness-32.jpg", name: "All Ages Camping — WDW Fort Wilderness 32", description: "Sifting for treasure" },
      { path: "/albums/ft-wilderness/ft-wilderness-33.jpg", name: "All Ages Camping — WDW Fort Wilderness 33", description: "Camping out in the car" },
      { path: "/albums/ft-wilderness/ft-wilderness-34.jpg", name: "All Ages Camping — WDW Fort Wilderness 34", description: "Around the fire pit" },
      { path: "/albums/ft-wilderness/ft-wilderness-35.jpg", name: "All Ages Camping — WDW Fort Wilderness 35", description: "Sleeping bags in a pile" },
      { path: "/albums/ft-wilderness/ft-wilderness-36.jpg", name: "All Ages Camping — WDW Fort Wilderness 36", description: "At the gem mine" },
      { path: "/albums/ft-wilderness/ft-wilderness-37.jpg", name: "All Ages Camping — WDW Fort Wilderness 37", description: "Leaders on the trip" },
      { path: "/albums/ft-wilderness/ft-wilderness-38.jpg", name: "All Ages Camping — WDW Fort Wilderness 38", description: "Loaded up and rolling" },
      { path: "/albums/ft-wilderness/ft-wilderness-39.jpg", name: "All Ages Camping — WDW Fort Wilderness 39", description: "Bundled up for the night" },
      { path: "/albums/ft-wilderness/ft-wilderness-40.jpg", name: "All Ages Camping — WDW Fort Wilderness 40", description: "Panning for gems together" },
      { path: "/albums/ft-wilderness/ft-wilderness-41.jpg", name: "All Ages Camping — WDW Fort Wilderness 41", description: "Arcade time" },
      { path: "/albums/ft-wilderness/ft-wilderness-42.jpg", name: "All Ages Camping — WDW Fort Wilderness 42", description: "Camp set up in the pines" },
      { path: "/albums/ft-wilderness/ft-wilderness-43.jpg", name: "All Ages Camping — WDW Fort Wilderness 43", description: "Horseback riding" },
      { path: "/albums/ft-wilderness/ft-wilderness-44.jpg", name: "All Ages Camping — WDW Fort Wilderness 44", description: "Meeting the horses" },
      { path: "/albums/ft-wilderness/ft-wilderness-45.jpg", name: "All Ages Camping — WDW Fort Wilderness 45", description: "Tents pitched and ready" },
    ],
  },
  {
    name: "All Ages Camping — Scoutmasters Camporee",
    description: "The Scoutmasters Camporee at Markham Park. Pioneering projects and lashings, camp games, a big cookout, and wildlife along the water at sunset.",
    date: new Date(2026, 1, 13),
    photos: [
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-01.jpg", name: "All Ages Camping — Scoutmasters Camporee 1", description: "Arriving at the camporee" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-02.jpg", name: "All Ages Camping — Scoutmasters Camporee 2", description: "Around the fire at night" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-03.jpg", name: "All Ages Camping — Scoutmasters Camporee 3", description: "Settled in for the evening" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-04.jpg", name: "All Ages Camping — Scoutmasters Camporee 4", description: "Laying out the pioneering poles" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-05.jpg", name: "All Ages Camping — Scoutmasters Camporee 5", description: "Lunch under the big tent" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-06.jpg", name: "All Ages Camping — Scoutmasters Camporee 6", description: "Raising the Pack 365 gateway" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-07.jpg", name: "All Ages Camping — Scoutmasters Camporee 7", description: "Fireworks over camp" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-08.jpg", name: "All Ages Camping — Scoutmasters Camporee 8", description: "Hot dogs on the griddle" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-09.jpg", name: "All Ages Camping — Scoutmasters Camporee 9", description: "Camp kitchen at work" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-10.jpg", name: "All Ages Camping — Scoutmasters Camporee 10", description: "Sunset over the tents" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-11.jpg", name: "All Ages Camping — Scoutmasters Camporee 11", description: "Dinner under the canopy" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-12.jpg", name: "All Ages Camping — Scoutmasters Camporee 12", description: "Camp games in the field" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-13.jpg", name: "All Ages Camping — Scoutmasters Camporee 13", description: "Wading bird on the lake" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-14.jpg", name: "All Ages Camping — Scoutmasters Camporee 14", description: "Down by the water" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-15.jpg", name: "All Ages Camping — Scoutmasters Camporee 15", description: "Basketball at the park" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-16.jpg", name: "All Ages Camping — Scoutmasters Camporee 16", description: "Serving up dinner" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-17.jpg", name: "All Ages Camping — Scoutmasters Camporee 17", description: "On stage at the camporee" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-18.jpg", name: "All Ages Camping — Scoutmasters Camporee 18", description: "Circled around the fire" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-19.jpg", name: "All Ages Camping — Scoutmasters Camporee 19", description: "The Pack 365 crew" },
      { path: "/albums/scoutmasters-camporee/scoutmasters-camporee-20.jpg", name: "All Ages Camping — Scoutmasters Camporee 20", description: "Slacklining between the trees" },
    ],
  },
  {
    name: "Blue & Gold Dinner",
    description: "The Blue & Gold banquet at Waters Edge Elementary — the pack's birthday party. A potluck spread, a Pack 365 cake, gold balloons, and awards all around.",
    date: new Date(2026, 1, 26),
    photos: [
      { path: "/albums/blue-and-gold/blue-and-gold-01.jpg", name: "Blue & Gold Dinner 1", description: "Dinner in the cafeteria" },
      { path: "/albums/blue-and-gold/blue-and-gold-02.jpg", name: "Blue & Gold Dinner 2", description: "Plates full at the table" },
      { path: "/albums/blue-and-gold/blue-and-gold-03.jpg", name: "Blue & Gold Dinner 3", description: "Leaders at the banquet" },
      { path: "/albums/blue-and-gold/blue-and-gold-04.jpg", name: "Blue & Gold Dinner 4", description: "Gold and blue table settings" },
      { path: "/albums/blue-and-gold/blue-and-gold-05.jpg", name: "Blue & Gold Dinner 5", description: "Cheers to the pack" },
      { path: "/albums/blue-and-gold/blue-and-gold-06.jpg", name: "Blue & Gold Dinner 6", description: "Dinner with friends" },
      { path: "/albums/blue-and-gold/blue-and-gold-07.jpg", name: "Blue & Gold Dinner 7", description: "The potluck line" },
      { path: "/albums/blue-and-gold/blue-and-gold-08.jpg", name: "Blue & Gold Dinner 8", description: "Balloons over the buffet" },
      { path: "/albums/blue-and-gold/blue-and-gold-09.jpg", name: "Blue & Gold Dinner 9", description: "In front of the 365 backdrop" },
      { path: "/albums/blue-and-gold/blue-and-gold-10.jpg", name: "Blue & Gold Dinner 10", description: "Working through the buffet" },
      { path: "/albums/blue-and-gold/blue-and-gold-11.jpg", name: "Blue & Gold Dinner 11", description: "The whole pack together" },
      { path: "/albums/blue-and-gold/blue-and-gold-12.jpg", name: "Blue & Gold Dinner 12", description: "Holding up the 365" },
      { path: "/albums/blue-and-gold/blue-and-gold-13.jpg", name: "Blue & Gold Dinner 13", description: "Pack 365 Blue & Gold cake" },
    ],
  },
  {
    name: "Pinewood Derby & MMT Hike",
    description: "Campout weekend at Tanah Keeta with the main event: the Pinewood Derby. Cars weighed in, the track went up, and between heats there was gaga ball, hiking, and s'mores.",
    date: new Date(2026, 2, 13),
    photos: [
      { path: "/albums/pinewood-derby/pinewood-derby-01.jpg", name: "Pinewood Derby & MMT Hike 1", description: "Gaga ball at the campsite" },
      { path: "/albums/pinewood-derby/pinewood-derby-02.jpg", name: "Pinewood Derby & MMT Hike 2", description: "Working on the cars" },
      { path: "/albums/pinewood-derby/pinewood-derby-03.jpg", name: "Pinewood Derby & MMT Hike 3", description: "Cars lined up for weigh-in" },
      { path: "/albums/pinewood-derby/pinewood-derby-04.jpg", name: "Pinewood Derby & MMT Hike 4", description: "Waiting for the next heat" },
      { path: "/albums/pinewood-derby/pinewood-derby-05.jpg", name: "Pinewood Derby & MMT Hike 5", description: "Pitching the tent" },
      { path: "/albums/pinewood-derby/pinewood-derby-06.jpg", name: "Pinewood Derby & MMT Hike 6", description: "Carrying the track" },
      { path: "/albums/pinewood-derby/pinewood-derby-07.jpg", name: "Pinewood Derby & MMT Hike 7", description: "Scooter around camp" },
      { path: "/albums/pinewood-derby/pinewood-derby-08.jpg", name: "Pinewood Derby & MMT Hike 8", description: "Flexing for the camera" },
      { path: "/albums/pinewood-derby/pinewood-derby-09.jpg", name: "Pinewood Derby & MMT Hike 9", description: "Setting up the finish line" },
      { path: "/albums/pinewood-derby/pinewood-derby-10.jpg", name: "Pinewood Derby & MMT Hike 10", description: "Timer at the finish" },
      { path: "/albums/pinewood-derby/pinewood-derby-11.jpg", name: "Pinewood Derby & MMT Hike 11", description: "Cars at the top of the track" },
      { path: "/albums/pinewood-derby/pinewood-derby-12.jpg", name: "Pinewood Derby & MMT Hike 12", description: "Gaga pit in the pines" },
      { path: "/albums/pinewood-derby/pinewood-derby-13.jpg", name: "Pinewood Derby & MMT Hike 13", description: "Gaga ball" },
      { path: "/albums/pinewood-derby/pinewood-derby-14.jpg", name: "Pinewood Derby & MMT Hike 14", description: "Sand between the heats" },
      { path: "/albums/pinewood-derby/pinewood-derby-15.jpg", name: "Pinewood Derby & MMT Hike 15", description: "Kickball in the clearing" },
      { path: "/albums/pinewood-derby/pinewood-derby-16.jpg", name: "Pinewood Derby & MMT Hike 16", description: "Tuning the cars" },
      { path: "/albums/pinewood-derby/pinewood-derby-17.jpg", name: "Pinewood Derby & MMT Hike 17", description: "Checking the wheels" },
      { path: "/albums/pinewood-derby/pinewood-derby-18.jpg", name: "Pinewood Derby & MMT Hike 18", description: "Testing the water bath" },
      { path: "/albums/pinewood-derby/pinewood-derby-19.jpg", name: "Pinewood Derby & MMT Hike 19", description: "Assembling the track" },
      { path: "/albums/pinewood-derby/pinewood-derby-20.jpg", name: "Pinewood Derby & MMT Hike 20", description: "The whole pack at the derby" },
      { path: "/albums/pinewood-derby/pinewood-derby-21.jpg", name: "Pinewood Derby & MMT Hike 21", description: "Fire pit at the campsite" },
      { path: "/albums/pinewood-derby/pinewood-derby-22.jpg", name: "Pinewood Derby & MMT Hike 22", description: "S'mores after the races" },
      { path: "/albums/pinewood-derby/pinewood-derby-23.jpg", name: "Pinewood Derby & MMT Hike 23", description: "Camp set up for the weekend" },
    ],
  },
  {
    name: "Kennedy Space Center Overnight",
    description: "An overnight at the Kennedy Space Center Visitor Complex. Scouts took on engineering challenges, climbed into the shuttle simulators, met the Orion capsule, and slept beneath the rockets.",
    date: new Date(2026, 3, 11),
    photos: [
      { path: "/albums/kennedy-space-center/kennedy-space-center-01.jpg", name: "Kennedy Space Center Overnight 1", description: "Arriving at the visitor complex" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-02.jpg", name: "Kennedy Space Center Overnight 2", description: "At the NASA globe" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-03.jpg", name: "Kennedy Space Center Overnight 3", description: "Spacesuit exhibit" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-04.jpg", name: "Kennedy Space Center Overnight 4", description: "Shuttle stack outside" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-05.jpg", name: "Kennedy Space Center Overnight 5", description: "Under the orbiter" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-06.jpg", name: "Kennedy Space Center Overnight 6", description: "In the cockpit simulator" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-07.jpg", name: "Kennedy Space Center Overnight 7", description: "The crew at the exhibit" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-08.jpg", name: "Kennedy Space Center Overnight 8", description: "Down the slide" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-09.jpg", name: "Kennedy Space Center Overnight 9", description: "Sliding the launch curve" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-10.jpg", name: "Kennedy Space Center Overnight 10", description: "Waiting for a turn" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-11.jpg", name: "Kennedy Space Center Overnight 11", description: "The Orion capsule" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-12.jpg", name: "Kennedy Space Center Overnight 12", description: "Bridge build complete" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-13.jpg", name: "Kennedy Space Center Overnight 13", description: "Showing off the truss" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-14.jpg", name: "Kennedy Space Center Overnight 14", description: "Engineering team, mission accomplished" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-15.jpg", name: "Kennedy Space Center Overnight 15", description: "Bunks beside the Astrovan" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-16.jpg", name: "Kennedy Space Center Overnight 16", description: "Movie under the shuttle" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-17.jpg", name: "Kennedy Space Center Overnight 17", description: "Atlantis up close" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-18.jpg", name: "Kennedy Space Center Overnight 18", description: "The group with Atlantis" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-19.jpg", name: "Kennedy Space Center Overnight 19", description: "Down the big slide" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-20.jpg", name: "Kennedy Space Center Overnight 20", description: "Two at a time" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-21.jpg", name: "Kennedy Space Center Overnight 21", description: "Working on the build" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-22.jpg", name: "Kennedy Space Center Overnight 22", description: "Racing down the slide" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-23.jpg", name: "Kennedy Space Center Overnight 23", description: "Leaders take a turn" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-24.jpg", name: "Kennedy Space Center Overnight 24", description: "Side by side descent" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-25.jpg", name: "Kennedy Space Center Overnight 25", description: "Sliding together" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-26.jpg", name: "Kennedy Space Center Overnight 26", description: "Laughing at the bottom" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-27.jpg", name: "Kennedy Space Center Overnight 27", description: "Truss bridge, finished" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-28.jpg", name: "Kennedy Space Center Overnight 28", description: "One more run" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-29.jpg", name: "Kennedy Space Center Overnight 29", description: "Bridge builders" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-30.jpg", name: "Kennedy Space Center Overnight 30", description: "Comparing designs" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-31.jpg", name: "Kennedy Space Center Overnight 31", description: "Full speed down" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-32.jpg", name: "Kennedy Space Center Overnight 32", description: "Walking the complex" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-33.jpg", name: "Kennedy Space Center Overnight 33", description: "Rocket Garden selfie" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-34.jpg", name: "Kennedy Space Center Overnight 34", description: "Gathered at the exhibit" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-35.jpg", name: "Kennedy Space Center Overnight 35", description: "The whole group at the globe" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-36.jpg", name: "Kennedy Space Center Overnight 36", description: "Rockets in the garden" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-37.jpg", name: "Kennedy Space Center Overnight 37", description: "Standing on Mars" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-38.jpg", name: "Kennedy Space Center Overnight 38", description: "Climbing the launch tower" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-39.jpg", name: "Kennedy Space Center Overnight 39", description: "Saturn V engines overhead" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-40.jpg", name: "Kennedy Space Center Overnight 40", description: "Out at the viewing area" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-41.jpg", name: "Kennedy Space Center Overnight 41", description: "Leaders at the complex" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-42.jpg", name: "Kennedy Space Center Overnight 42", description: "Inside the space station module" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-43.jpg", name: "Kennedy Space Center Overnight 43", description: "Moon landing exhibit" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-44.jpg", name: "Kennedy Space Center Overnight 44", description: "Pillow fight in the bunk room" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-45.jpg", name: "Kennedy Space Center Overnight 45", description: "Welcome Home exhibit" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-46.jpg", name: "Kennedy Space Center Overnight 46", description: "In front of the orbiter" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-47.jpg", name: "Kennedy Space Center Overnight 47", description: "At the Explore entrance" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-48.jpg", name: "Kennedy Space Center Overnight 48", description: "Break at the picnic tables" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-49.jpg", name: "Kennedy Space Center Overnight 49", description: "Sitting in the capsule hatch" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-50.jpg", name: "Kennedy Space Center Overnight 50", description: "Under the shuttle stack" },
      { path: "/albums/kennedy-space-center/kennedy-space-center-51.jpg", name: "Kennedy Space Center Overnight 51", description: "Bus tour to the pads" },
    ],
  },
  {
    name: "Pack & Den Meetings",
    description: "A year of Pack 365 den meetings and awards ceremonies across Waters Edge and Sandpiper Shores, plus nature-trail hikes and craft nights. Rank badges, belt loops, and a lot of friends made along the way.",
    date: new Date(2026, 4, 14),
    photos: [
      { path: "/albums/pack-meetings/pack-meetings-01.jpg", name: "Pack & Den Meetings 1", description: "Den meeting around the table" },
      { path: "/albums/pack-meetings/pack-meetings-02.jpg", name: "Pack & Den Meetings 2", description: "Color guard at the pack meeting" },
      { path: "/albums/pack-meetings/pack-meetings-03.jpg", name: "Pack & Den Meetings 3", description: "Face paint at the meeting" },
      { path: "/albums/pack-meetings/pack-meetings-04.jpg", name: "Pack & Den Meetings 4", description: "Leaders and scouts" },
      { path: "/albums/pack-meetings/pack-meetings-05.jpg", name: "Pack & Den Meetings 5", description: "Receiving awards on stage" },
      { path: "/albums/pack-meetings/pack-meetings-06.jpg", name: "Pack & Den Meetings 6", description: "Den photo after the ceremony" },
      { path: "/albums/pack-meetings/pack-meetings-07.jpg", name: "Pack & Den Meetings 7", description: "Handing out the awards" },
      { path: "/albums/pack-meetings/pack-meetings-08.jpg", name: "Pack & Den Meetings 8", description: "Neckerchief presentation" },
      { path: "/albums/pack-meetings/pack-meetings-09.jpg", name: "Pack & Den Meetings 9", description: "Out on the boardwalk" },
      { path: "/albums/pack-meetings/pack-meetings-10.jpg", name: "Pack & Den Meetings 10", description: "Cathy Burdett Nature Trail" },
      { path: "/albums/pack-meetings/pack-meetings-11.jpg", name: "Pack & Den Meetings 11", description: "Learning to fold the flag" },
      { path: "/albums/pack-meetings/pack-meetings-12.jpg", name: "Pack & Den Meetings 12", description: "Flag folding practice" },
      { path: "/albums/pack-meetings/pack-meetings-13.jpg", name: "Pack & Den Meetings 13", description: "Presenting the folded flag" },
      { path: "/albums/pack-meetings/pack-meetings-14.jpg", name: "Pack & Den Meetings 14", description: "Cleanup crew with the bags" },
      { path: "/albums/pack-meetings/pack-meetings-15.jpg", name: "Pack & Den Meetings 15", description: "Painting at the picnic table" },
      { path: "/albums/pack-meetings/pack-meetings-16.jpg", name: "Pack & Den Meetings 16", description: "Recruiting table at the store" },
      { path: "/albums/pack-meetings/pack-meetings-17.jpg", name: "Pack & Den Meetings 17", description: "Show and sell team" },
      { path: "/albums/pack-meetings/pack-meetings-18.jpg", name: "Pack & Den Meetings 18", description: "Awards on stage" },
      { path: "/albums/pack-meetings/pack-meetings-19.jpg", name: "Pack & Den Meetings 19", description: "Rank advancement" },
      { path: "/albums/pack-meetings/pack-meetings-20.jpg", name: "Pack & Den Meetings 20", description: "Another round of awards" },
      { path: "/albums/pack-meetings/pack-meetings-21.jpg", name: "Pack & Den Meetings 21", description: "Den with their leader" },
      { path: "/albums/pack-meetings/pack-meetings-22.jpg", name: "Pack & Den Meetings 22", description: "The whole den on stage" },
      { path: "/albums/pack-meetings/pack-meetings-23.jpg", name: "Pack & Den Meetings 23", description: "Two scouts, awards in hand" },
      { path: "/albums/pack-meetings/pack-meetings-24.jpg", name: "Pack & Den Meetings 24", description: "Working through the requirements" },
      { path: "/albums/pack-meetings/pack-meetings-25.jpg", name: "Pack & Den Meetings 25", description: "Working on a craft" },
      { path: "/albums/pack-meetings/pack-meetings-26.jpg", name: "Pack & Den Meetings 26", description: "Getting a hand with the build" },
      { path: "/albums/pack-meetings/pack-meetings-27.jpg", name: "Pack & Den Meetings 27", description: "Carving away" },
      { path: "/albums/pack-meetings/pack-meetings-28.jpg", name: "Pack & Den Meetings 28", description: "Focused on the project" },
      { path: "/albums/pack-meetings/pack-meetings-29.jpg", name: "Pack & Den Meetings 29", description: "All smiles at the meeting" },
      { path: "/albums/pack-meetings/pack-meetings-30.jpg", name: "Pack & Den Meetings 30", description: "The whole pack, Class A" },
      { path: "/albums/pack-meetings/pack-meetings-31.jpg", name: "Pack & Den Meetings 31", description: "Group photo in the cafeteria" },
      { path: "/albums/pack-meetings/pack-meetings-32.jpg", name: "Pack & Den Meetings 32", description: "Craft night in full swing" },
      { path: "/albums/pack-meetings/pack-meetings-33.jpg", name: "Pack & Den Meetings 33", description: "Color guard practice" },
      { path: "/albums/pack-meetings/pack-meetings-34.jpg", name: "Pack & Den Meetings 34", description: "Painting projects" },
      { path: "/albums/pack-meetings/pack-meetings-35.jpg", name: "Pack & Den Meetings 35", description: "Sanding the block" },
      { path: "/albums/pack-meetings/pack-meetings-36.jpg", name: "Pack & Den Meetings 36", description: "Showing off the build" },
      { path: "/albums/pack-meetings/pack-meetings-37.jpg", name: "Pack & Den Meetings 37", description: "Working on the derby car" },
      { path: "/albums/pack-meetings/pack-meetings-38.jpg", name: "Pack & Den Meetings 38", description: "Test fitting the pieces" },
      { path: "/albums/pack-meetings/pack-meetings-39.jpg", name: "Pack & Den Meetings 39", description: "Setting up outside" },
      { path: "/albums/pack-meetings/pack-meetings-40.jpg", name: "Pack & Den Meetings 40", description: "Decorating the cars" },
      { path: "/albums/pack-meetings/pack-meetings-41.jpg", name: "Pack & Den Meetings 41", description: "Gluing it together" },
      { path: "/albums/pack-meetings/pack-meetings-42.jpg", name: "Pack & Den Meetings 42", description: "Working through the packets" },
      { path: "/albums/pack-meetings/pack-meetings-43.jpg", name: "Pack & Den Meetings 43", description: "Spartan Kids finish line" },
      { path: "/albums/pack-meetings/pack-meetings-44.jpg", name: "Pack & Den Meetings 44", description: "Awards on the risers" },
      { path: "/albums/pack-meetings/pack-meetings-45.jpg", name: "Pack & Den Meetings 45", description: "Den leader and her scouts" },
      { path: "/albums/pack-meetings/pack-meetings-46.jpg", name: "Pack & Den Meetings 46", description: "The den on the podium" },
      { path: "/albums/pack-meetings/pack-meetings-47.jpg", name: "Pack & Den Meetings 47", description: "Everyone up front" },
    ],
  },
];

export { eventList };
